version: "3.8"
services:
  mongo:
    image: mongo:5.0.13
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-admin}
      - MONGO_INITDB_ROOT_DATABASE=${MONGO_ROOT_DB:-mongodb}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-test}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME:-admin}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD:-admin}
      - SALES_PASSWORD=${SALES_PASSWORD:-sales}
      - WAREHOUSE_PASSWORD=${WAREHOUSE_PASSWORD:-warehouse}      
    volumes:
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      
    networks:
      - main-network

    
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    networks:
      - main-network      
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-admin}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin}@mongo:27017/    
volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
networks:
  main-network:
    name: ${MONGO_NETWORK:-mongodb.network}    
    
  
